services:
  garnet:
    container_name: garnet
    image: "ghcr.io/microsoft/garnet"
    user: "1000:1000"
    restart: always
    ulimits:
      memlock: -1
    command: [ "--auth", "Password", "--password", "${GARNET_PASSWORD}", "--storage-tier", "--logdir", "/logs", "--aof", "--port", "6380" ]
    ports:
      - "6380:6380"
    volumes:
      - /Docker/ttvdrops/Garnet/data:/data
      - /Docker/ttvdrops/Garnet/logs:/logs
    networks:
      - ttvdrops_garnet

  postgres:
    container_name: ttvdrops_postgres
    image: postgres:16
    user: "1000:1000"
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /Docker/ttvdrops/Postgres:/var/lib/postgresql/data
    networks:
      - ttvdrops_db

networks:
  ttvdrops_garnet:
  ttvdrops_db:
