# Generated by Django 5.1 on 2024-09-02 23:28

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.RenameField(
            model_name="dropcampaign",
            old_name="id",
            new_name="twitch_id",
        ),
    ]
