# Generated by Django 5.0.6 on 2024-07-01 01:10

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.RemoveField(
            model_name="discordsetting",
            name="notification_type",
        ),
        migrations.AddField(
            model_name="discordsetting",
            name="name",
            field=models.CharField(default="No name", max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="NotificationType",
        ),
    ]
