# Generated by Django 5.1 on 2024-09-01 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Channel",
        ),
    ]
