# Generated by Django 5.1 on 2024-08-12 22:19

import auto_prefetch
import django.db.models.deletion
from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="benefit",
            name="time_based_drop",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefits",
                to="core.timebaseddrop",
            ),
        ),
        migrations.AlterField(
            model_name="dropcampaign",
            name="game",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drop_campaigns",
                to="core.game",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="org",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="core.owner",
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="campaign",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rewards",
                to="core.rewardcampaign",
            ),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="game",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_campaigns",
                to="core.game",
            ),
        ),
        migrations.AlterField(
            model_name="timebaseddrop",
            name="drop_campaign",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drops",
                to="core.dropcampaign",
            ),
        ),
    ]
