# Generated by Django 5.1.4 on 2024-12-16 18:31
from __future__ import annotations

import datetime
from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """This migration alters the created_at field on the Benefit, DropCampaign, Owner, and TimeBasedDrop models."""

    dependencies: list[tuple[str, str]] = [
        ("core", "0002_alter_user_options"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="benefit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 12, 16, 18, 31, 14, 851533, tzinfo=datetime.UTC),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dropcampaign",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the drop campaign was first added to the database.",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="timebaseddrop",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When the drop was first added to the database."),
        ),
    ]
