# Generated by Django 5.1 on 2024-09-07 19:19
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0002_rename_id_dropcampaign_twitch_id"),
    ]

    operations: list[Operation] = [
        migrations.RenameField(
            model_name="rewardcampaign",
            old_name="sub_goal",
            new_name="subs_goal",
        ),
    ]
