# Generated by Django 5.1 on 2024-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_squashed_0003_alter_benefit_options_alter_channel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="display_name",
            field=models.TextField(default="Channel name unknown", null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="twitch_url",
            field=models.URLField(default="https://www.twitch.tv/", null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="box_art_url",
            field=models.URLField(default="https://static-cdn.jtvnw.net/ttv-static/404_boxart.jpg", null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_url",
            field=models.URLField(default="https://www.twitch.tv/", null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.TextField(default="Game name unknown", null=True),
        ),
    ]
