# Generated by Django 5.1.4 on 2024-12-18 22:35
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Fix created_at using auto_created instead of auto_now_add."""

    dependencies: list[tuple[str, str]] = [
        ("core", "0003_alter_benefit_created_at_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When the game was first added to the database."),
        ),
    ]
