# Generated by Django 5.1 on 2024-09-09 02:34

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0003_rename_sub_goal_rewardcampaign_subs_goal"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="dropcampaign",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="box_art_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="timebaseddrop",
            name="name",
            field=models.TextField(null=True),
        ),
    ]
