# Generated by Django 5.0.6 on 2024-07-01 21:47

import django.utils.timezone
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0004_historicaldiscordsetting_historicalsubscription"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="discordsetting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldiscordsetting",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
            ),
            preserve_default=False,
        ),
    ]
