# Generated by Django 5.1.1 on 2024-09-16 19:32
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

import core.models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0005_alter_benefit_options_alter_dropcampaign_options_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="benefit",
            name="image",
            field=models.ImageField(null=True, upload_to=core.models.get_benefit_image_path),
        ),
        migrations.AddField(
            model_name="dropcampaign",
            name="image",
            field=models.ImageField(null=True, upload_to=core.models.get_drop_campaign_image_path),
        ),
        migrations.AddField(
            model_name="game",
            name="image",
            field=models.ImageField(null=True, upload_to=core.models.get_game_image_path),
        ),
        migrations.AddField(
            model_name="reward",
            name="banner_image",
            field=models.ImageField(null=True, upload_to=core.models.get_reward_banner_image_path),
        ),
        migrations.AddField(
            model_name="reward",
            name="thumbnail_image",
            field=models.ImageField(null=True, upload_to=core.models.get_reward_thumbnail_image_path),
        ),
        migrations.AddField(
            model_name="rewardcampaign",
            name="image",
            field=models.ImageField(null=True, upload_to=core.models.get_reward_image_path),
        ),
    ]
