# Generated by Django 5.1.1 on 2024-09-21 00:08
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0006_benefit_image_dropcampaign_image_game_image_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="owner",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.TextField(null=True, unique=True),
        ),
    ]
