# Generated by Django 5.1.1 on 2024-09-21 16:51
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("core", "0007_alter_game_options_alter_owner_options_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="dropcampaign",
            name="scraped_json",
            field=models.JSONField(help_text="The JSON data from the Twitch API.", null=True),
        ),
        migrations.AddField(
            model_name="rewardcampaign",
            name="scraped_json",
            field=models.JSONField(help_text="The JSON data from the Twitch API.", null=True),
        ),
    ]
