# Generated by Django 5.1a1 on 2024-06-22 03:14

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.AlterModelOptions(
            name="dropcampaign",
            options={"verbose_name_plural": "Drop Campaigns"},
        ),
        migrations.AlterField(
            model_name="dropcampaign",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drop_campaigns",
                to="twitch.game",
            ),
        ),
        migrations.AlterField(
            model_name="dropcampaign",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drop_campaigns",
                to="twitch.organization",
            ),
        ),
    ]
