# Generated by Django 5.1a1 on 2024-06-22 19:27

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch", "0003_channel_added_at_channel_modified_at_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterModelOptions(
            name="dropcampaign",
            options={},
        ),
    ]
