# Generated by Django 5.1a1 on 2024-06-22 20:05

import django.db.models.functions.text
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch", "0004_alter_dropcampaign_options"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="game",
            name="twitch_url",
            field=models.GeneratedField(  # type: ignore  # noqa: PGH003
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    models.Value("https://www.twitch.tv/directory/category/"),
                    "slug",
                ),
                output_field=models.TextField(),
            ),
        ),
    ]
