# Generated by Django 5.1rc1 on 2024-07-30 23:39

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch_app", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="rewardcampaign",
            name="about_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="brand",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="external_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_campaigns",
                to="twitch_app.game",
            ),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_campaigns",
                to="twitch_app.image",
            ),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="is_sitewide",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="reward_value_url_param",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="typename",
            field=models.TextField(blank=True, null=True),
        ),
    ]
