# Generated by Django 5.0.6 on 2024-07-01 15:23

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch_app", "0003_historicaldropbenefit_historicaldropcampaign_and_more"),
    ]

    operations: list[Operation] = [
        migrations.RemoveField(
            model_name="user",
            name="drop_campaigns",
        ),
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
