# Generated by Django 5.1rc1 on 2024-07-30 23:44

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch_app", "0003_alter_game_display_name_alter_game_slug_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="reward",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
