# Generated by Django 5.0.6 on 2024-07-01 15:40

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        (
            "twitch_app",
            "0004_remove_user_drop_campaigns_delete_historicaluser_and_more",
        ),
    ]

    operations: list[Operation] = [
        migrations.AlterModelOptions(
            name="dropbenefit",
            options={
                "ordering": ("name",),
                "verbose_name": "Drop Benefit",
                "verbose_name_plural": "Drop Benefits",
            },
        ),
        migrations.AlterModelOptions(
            name="dropcampaign",
            options={
                "ordering": ("name",),
                "verbose_name": "Drop Campaign",
                "verbose_name_plural": "Drop Campaigns",
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ("display_name",),
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldropbenefit",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Drop Benefit",
                "verbose_name_plural": "historical Drop Benefits",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldropcampaign",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Drop Campaign",
                "verbose_name_plural": "historical Drop Campaigns",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalgame",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Game",
                "verbose_name_plural": "historical Games",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltimebaseddrop",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Time-Based Drop",
                "verbose_name_plural": "historical Time-Based Drops",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("name",),
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="timebaseddrop",
            options={
                "ordering": ("name",),
                "verbose_name": "Time-Based Drop",
                "verbose_name_plural": "Time-Based Drops",
            },
        ),
    ]
