# Generated by Django 5.1rc1 on 2024-08-01 02:50

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch_app", "0005_channel_owner_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="rewardcampaign",
            name="unlock_requirements",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_campaigns",
                to="twitch_app.unlockrequirements",
            ),
        ),
        migrations.AlterField(
            model_name="dropcampaign",
            name="time_based_drops",
            field=models.ManyToManyField(null=True, related_name="drop_campaigns", to="twitch_app.timebaseddrop"),
        ),
        migrations.AlterField(
            model_name="reward",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
