# Generated by Django 5.0.6 on 2024-07-02 17:11

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch_app", "0006_alter_dropbenefit_options_alter_dropcampaign_options_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="dropcampaign",
            name="time_based_drops",
            field=models.ManyToManyField(related_name="drop_campaigns", to="twitch_app.timebaseddrop"),
        ),
        migrations.AlterField(
            model_name="timebaseddrop",
            name="benefits",
            field=models.ManyToManyField(related_name="time_based_drops", to="twitch_app.dropbenefit"),
        ),
    ]
