# Generated by Django 5.1rc1 on 2024-08-01 14:15

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch_app", "0006_rewardcampaign_unlock_requirements_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="dropcampaign",
            name="time_based_drops",
            field=models.ManyToManyField(related_name="drop_campaigns", to="twitch_app.timebaseddrop"),
        ),
    ]
