# Generated by Django 5.0.6 on 2024-07-03 21:19

import auto_prefetch
import django.db.models.deletion
from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch_app", "0007_alter_dropcampaign_time_based_drops_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="dropbenefit",
            name="game",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drop_benefits",
                to="twitch_app.game",
            ),
        ),
        migrations.AlterField(
            model_name="dropbenefit",
            name="owner_organization",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drop_benefits",
                to="twitch_app.organization",
            ),
        ),
    ]
