# Generated by Django 5.1rc1 on 2024-08-01 14:48

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("twitch_app", "0008_alter_allow_options_alter_benefit_options_and_more"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="benefit",
            name="entitlement_limit",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="benefitedge",
            name="entitlement_limit",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="owner",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="timebaseddrop",
            name="entitlement_limit",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="unlockrequirements",
            name="minute_watched_goal",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="unlockrequirements",
            name="subs_goal",
            field=models.TextField(null=True),
        ),
    ]
